image: node

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - "which ssh-agent || ( apt-get install -qq openssh-client )"
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy:
  stage: deploy
  environment:
    name: dev
    url: dev.saris.com
  script:
    - ssh -o StrictHostKeyChecking=no sarissfptuser@23.22.32.84 "cd /var/www/saris/frontend; git stash; git pull origin master; npm install; source deploy.sh;"
  only:
    - master
